// Code generated by wit-bindgen-go. DO NOT EDIT.

package callbackshost

// This file contains wasmimport and wasmexport declarations for "jcbhmr:hello".

//go:wasmimport jcbhmr:hello/callbacks-host [resource-drop]P-string
//go:noescape
func wasmimport_PStringResourceDrop(self0 uint32)

//go:wasmimport jcbhmr:hello/callbacks-host [method]P-string.call
//go:noescape
func wasmimport_PStringCall(self0 uint32, a0 *uint8, a1 uint32)

//go:wasmimport jcbhmr:hello/callbacks-host [resource-drop]P-string-R-string
//go:noescape
func wasmimport_PStringRStringResourceDrop(self0 uint32)

//go:wasmimport jcbhmr:hello/callbacks-host [method]P-string-R-string.call
//go:noescape
func wasmimport_PStringRStringCall(self0 uint32, a0 *uint8, a1 uint32, result *string)

//go:wasmimport jcbhmr:hello/callbacks-host [resource-drop]P-any
//go:noescape
func wasmimport_PAnyResourceDrop(self0 uint32)

//go:wasmimport jcbhmr:hello/callbacks-host [method]P-any.call
//go:noescape
func wasmimport_PAnyCall(self0 uint32, a0 uint32)
