// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package x represents the imported interface "jcbhmr:hello/x".
package x

// Any represents the s32 "jcbhmr:hello/x#any".
//
//	type any = s32
type Any int32
