// Code generated by wit-bindgen-go. DO NOT EDIT.

package greetings

// Exports represents the caller-defined exports from "jcbhmr:hello-world/greetings".
var Exports struct {
	// SayHello represents the caller-defined, exported function "say-hello".
	//
	//	say-hello: func(name: string)
	SayHello func(name string)

	// SayHi represents the caller-defined, exported function "say-hi".
	//
	//	say-hi: func(name: string)
	SayHi func(name string)

	// SayHiInFrench represents the caller-defined, exported function "say-hi-in-french".
	//
	//	say-hi-in-french: func(name: string)
	SayHiInFrench func(name string)
}
