// Code generated by wit-bindgen-go. DO NOT EDIT.

package greetings

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "jcbhmr:hello-world".

//go:wasmexport jcbhmr:hello-world/greetings#say-hello
//export jcbhmr:hello-world/greetings#say-hello
func wasmexport_SayHello(name0 *uint8, name1 uint32) {
	name := cm.LiftString[string]((*uint8)(name0), (uint32)(name1))
	Exports.SayHello(name)
	return
}

//go:wasmexport jcbhmr:hello-world/greetings#say-hi
//export jcbhmr:hello-world/greetings#say-hi
func wasmexport_SayHi(name0 *uint8, name1 uint32) {
	name := cm.LiftString[string]((*uint8)(name0), (uint32)(name1))
	Exports.SayHi(name)
	return
}

//go:wasmexport jcbhmr:hello-world/greetings#say-hi-in-french
//export jcbhmr:hello-world/greetings#say-hi-in-french
func wasmexport_SayHiInFrench(name0 *uint8, name1 uint32) {
	name := cm.LiftString[string]((*uint8)(name0), (uint32)(name1))
	Exports.SayHiInFrench(name)
	return
}
